#screen settings
TILEWIDTH = 16
TILEHEIGHT = 16
GRIDROWS = 36
GRIDCOLS = 28
SWIDTH = GRIDCOLS*TILEWIDTH
SHEIGHT = GRIDROWS*TILEHEIGHT
SCREENSIZE = (SWIDTH, SHEIGHT)

#colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)